# Makefile : Makefile
# Author: liubin <bin.lb@alipay.com>
# Created: 2011-06-16

# load config
TOP_DIR = .
include MK.config

.PHONY : all clean test

all :
	make -C src

test :
	make -C tests

clean :
	make -C src clean
	make -C tests clean
